name: ShopSphere - Build and Push

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  REGISTRY: docker.io
  IMAGE_NAME: dineshccs/shopsphere

jobs:

  build-push:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        service:
          - adservice
          - cartservice
          - checkoutservice
          - currencyservice
          - emailservice
          - frontend
          - loadgenerator
          - paymentservice
          - productcatalogservice
          - recommendationservice
          - shippingservice

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image tag
        id: image
        run: |
          echo "tag=${{ matrix.service }}-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:${{ steps.image.outputs.tag }} \
            ./application/${{ matrix.service }}

      - name: Push Docker image
        run: |
          docker push \
            $IMAGE_NAME:${{ steps.image.outputs.tag }}
